# Generated by Django 5.2.6 on 2025-09-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='DetalleVenta',
            new_name='DetalleVentas',
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Empleados',
        ),
        migrations.RenameModel(
            old_name='FacturaVenta',
            new_name='FacturaVentas',
        ),
        migrations.RenameModel(
            old_name='Movimiento',
            new_name='Movimientos',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Proveedores',
        ),
    ]
